# Generated by Django 5.2.11 on 2026-02-10 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "testrail_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("title", models.CharField(max_length=500)),
                ("template", models.CharField(default="Test Case", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Acceptance", "Acceptance"),
                            ("Accessibility", "Accessibility"),
                            ("Automated", "Automated"),
                            ("Compatibility", "Compatibility"),
                            ("Destructive", "Destructive"),
                            ("Functional", "Functional"),
                            ("Other", "Other"),
                            ("Performance", "Performance"),
                            ("Regression", "Regression"),
                            ("Security", "Security"),
                            ("Smoke & Sanity", "Smoke & Sanity"),
                            ("Usability", "Usability"),
                        ],
                        default="Functional",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("1 - Don't Test", "1 - Don't Test"),
                            ("2 - Test If Time", "2 - Test If Time"),
                            ("3 - Test If Time", "3 - Test If Time"),
                            ("4 - Must Test", "4 - Must Test"),
                            ("5 - Must Test", "5 - Must Test"),
                        ],
                        default="5 - Must Test",
                        max_length=50,
                    ),
                ),
                ("estimate", models.CharField(blank=True, default="", max_length=50)),
                (
                    "references",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("preconditions", models.TextField(blank=True, default="")),
                ("steps", models.TextField(blank=True, default="")),
                ("expected", models.TextField(blank=True, default="")),
                ("is_converted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
