# Generated by Django 5.2.11 on 2026-02-12 17:00

import django.db.models.deletion
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_testrun_testruntestcase_testrun_test_cases"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRunScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=projects.models._screenshot_upload_path
                    ),
                ),
                ("tool_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_run_test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="projects.testruntestcase",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
