# Generated by Django 5.2.11 on 2026-02-13 16:31

import secrets

from django.db import migrations, models


def populate_api_keys(apps, schema_editor):
    """Populate api_key for existing projects before adding unique constraint."""
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        if not project.api_key:
            project.api_key = secrets.token_urlsafe(32)
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_testrunscreenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="agent_connected",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="agent_system_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="last_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="api_key",
            field=models.CharField(
                blank=True, db_index=False, default="", max_length=64
            ),
        ),
        migrations.RunPython(populate_api_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="api_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64, unique=True
            ),
        ),
    ]
