# Generated by Django 5.2.11 on 2026-02-13 16:57

from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_agent_connected_project_agent_system_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="api_key",
            field=models.CharField(
                db_index=True,
                default=projects.models._default_api_key,
                max_length=64,
                unique=True,
            ),
        ),
    ]
