# Generated by Django 5.2.11 on 2026-02-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("started", "Started"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testruntestcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("in_progress", "In Progress"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
    ]
