# Generated by Django 5.2.11 on 2026-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_testrun_celery_task_id_alter_testrun_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testrun",
            name="project_prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
