# Generated by Django 5.2.11 on 2026-02-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_project_prompt_testrun_project_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testrun",
            name="project_prompt",
        ),
    ]
