# Generated by Django 5.2.17 on 2026-09-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_testrun_project_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="agent_capabilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="agent_client_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="project",
            name="agent_omniparser_status",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
