# Generated by Django 5.2.17 on 2026-09-07 18:30

from django.db import migrations, models
from django.db.models import F


def backfill_run_timestamps(apps, schema_editor):
    TestRun = apps.get_model("projects", "TestRun")
    TestRunTestCase = apps.get_model("projects", "TestRunTestCase")
    TestRun.objects.filter(status__in=["done", "cancelled"]).update(
        started_at=F("created_at"), finished_at=F("updated_at")
    )
    TestRun.objects.filter(status="started").update(started_at=F("created_at"))
    TestRunTestCase.objects.filter(
        status__in=["success", "failed", "cancelled"]
    ).update(started_at=F("created_at"), finished_at=F("updated_at"))


def reverse_backfill_run_timestamps(apps, schema_editor):
    apps.get_model("projects", "TestRun").objects.update(
        started_at=None, finished_at=None
    )
    apps.get_model("projects", "TestRunTestCase").objects.update(
        started_at=None, finished_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_add_agent_client_capabilities_omniparser_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="application_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("web", "Web application"),
                    ("windows", "Windows desktop"),
                    ("both", "Both"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="application_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="testrun",
            name="finished_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="testrun",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="testrun",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testruntestcase",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testruntestcase",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_run_timestamps, reverse_backfill_run_timestamps),
    ]
