# Generated by Django 5.2.17 on 2026-09-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_punk_hazard_context_and_run_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="testrail_api_key_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="testrail_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="project",
            name="testrail_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="testcaseupload",
            name="source",
            field=models.CharField(
                choices=[
                    ("xml", "TestRail XML export"),
                    ("testrail_api", "TestRail account"),
                ],
                db_index=True,
                default="xml",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testcaseupload",
            name="testrail_project_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testcaseupload",
            name="testrail_suite_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testcaseupload",
            name="updated_cases",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testcaseupload",
            name="file",
            field=models.FileField(blank=True, upload_to="uploads/testrail_xml/"),
        ),
    ]
