# Generated by Django 5.2.17 on 2026-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_testrail_api_import"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["project", "testrail_id"], name="testcase_project_testrail_idx"
            ),
        ),
    ]
