from __future__ import annotations

class VNCDoToolClient:
    def captureScreen(self, filename: str) -> VNCDoToolClient: ...
    def mouseMove(self, x: int, y: int) -> VNCDoToolClient: ...
    def mousePress(self, button: int) -> VNCDoToolClient: ...
    def mouseDown(self, button: int) -> VNCDoToolClient: ...
    def mouseUp(self, button: int) -> VNCDoToolClient: ...
    def keyPress(self, key: str) -> VNCDoToolClient: ...
    def type(self, text: str) -> VNCDoToolClient: ...
    def disconnect(self) -> VNCDoToolClient: ...

def connect(
    server: str, password: str | None = ..., timeout: int = ...
) -> VNCDoToolClient: ...
def shutdown() -> None: ...
