from typing import Any

class BaseChannelLayer:
    async def send(self, channel: str, message: dict[str, Any]) -> None: ...
    async def receive(self, channel: str) -> dict[str, Any]: ...
    async def new_channel(self, prefix: str = ...) -> str: ...
    async def group_send(self, group: str, message: dict[str, Any]) -> None: ...
    async def group_add(self, group: str, channel: str) -> None: ...
    async def group_discard(self, group: str, channel: str) -> None: ...

def get_channel_layer(alias: str = ...) -> BaseChannelLayer | None: ...
