from typing import Any

class WebsocketCommunicator:
    def __init__(self, application: Any, path: str, **kwargs: Any) -> None: ...
    async def connect(self, timeout: float = ...) -> tuple[bool, int | None]: ...
    async def send_to(self, text_data: str = ..., bytes_data: bytes = ...) -> None: ...
    async def send_json_to(self, data: Any) -> None: ...
    async def receive_from(self, timeout: float = ...) -> str: ...
    async def receive_json_from(self, timeout: float = ...) -> Any: ...
    async def disconnect(self, code: int = ..., timeout: float = ...) -> None: ...
